### ISSUE TITLE
Crashes on Android 6.0 (targetSdkVersion=23)

### ISSUE THREAD

**Issue by andersdp** [iotashan/TiTouchImageView#11]
App fails to launch when module is included in tiapp.xml but only on a real device - it works in Genymotion simulator.

What needs to be done in order to make the module run on a device with Android 6.0?

**Comment by maxdangelo** [comment]
Hi,

I have exactly the same issue, it works in Genymotion and crashes during launch.

**Comment by pke** [comment]
Crashes the app on devices running Android 6.0

> java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/de.evopark.evopark-1/lib/arm/liborg.iotashan.TiTouchImageView.so: has text relocations
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

**Comment by AppWerft** [comment]
I have similar issues:
If I embed the module in my app then to runtime appears: „Cannot find module“ if I call:
~~~

function getImageon(url, cb) {
	var $ = Ti.Network.createHTTPClient({
		onload : function() {
			cb(this.responseData);
		}
	});
	$.open('GET', url);
	$.send();
}

module.exports = function(species) {
	var $ = Ti.UI.createWindow({
		backgroundColor : 'transparent',
		title : '',
		theme : 'Theme.NoActionBar',
		fullscreen : true,
	});
	var TiTouchImageView = require('org.iotashan.titouchimageview');
	$.zoomView = TiTouchImageView.createView();
	getImage(species.bigimage, function(blob) {
		$.zoomView.image = blob;
	});
	$.add(zoomView);
	return $;
};

~~~
Second I tried to recompile. In this case I got errors with ndk. Here my build.properties:
~~~
titanium.platform=/Users/fuerst/Library/Application Support/Titanium/mobilesdk/osx/5.1.1.GA/android
android.platform=/Users/fuerst/Library/android-sdk-macosx/platforms/android-21
google.apis=/Users/fuerst/Library/android-sdk-macosx/add-ons/addon-google_apis-google-21
android.ndk=/Users/fuerst/Library/android-ndk-macosx/
~~~

**Comment by gimdongwoo** [comment]
I'm tested on Anroid 6.0.1 (Nexus 5) / Ti. SDK 5.1.2.GA.
but, it's ok. no error.

**Comment by gsoulie** [comment]
Hello, same issue this morning after updating my Appcelerator CLI to 5.2.0 + Studio 4.5.0, using 5.1.2.GA SDK on Android 6.0.1 (Nexus 6) :/ It works fine last week before updating CLI on same phone (Nexus 6, Android 6.0.1)

**Comment by echeung3** [comment]
Same issue here.

Looks like the build just needs to be recompiled with the latest NDK. Can we get a new build release?

Reference:
https://github.com/appcelerator-modules/ti.compression/issues/6
https://jira.appcelerator.org/browse/TIMOB-20071

**Comment by rollsroyc3** [comment]
Any movement on this? Or any other modules that provide similar functionality?

**Comment by AppWerft** [comment]
I'm using Ti.Touchgallery https://github.com/gbaldera/TiTouchGallery

**Comment by rollsroyc3** [comment]
Thanks. 
I updated the build.properties file and recompiled and it seems to be working for me now on 5.0.1.

**Comment by AppWerft** [comment]
Good message!

**Comment by SudoPlz** [comment]
@rollsroyc3  Can you please upload it and pull request, or whatever, I need this as well, I can't  run this on Titanium 5.2.2GA and I have no idea how to rebuild a module.

**Comment by rollsroyc3** [comment]
@SudoPlz Yeah I will when I get a chance, what error are you getting?

**Comment by gimdongwoo** [comment]
TiTouchImageView need to storage permisson on Android 6.0+.

Ti.SDK support request storage permission on Ti.SDK 5.4.0.

Therefore, using this module before 5.4.0.GA.
https://github.com/gimdongwoo/Ti-Android-RequestStoragePermission
